version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'monthly'
          day: 'thursday'
          time: '08:00'
          timezone: 'Europe/Amsterdam'
      groups:
          dependencies:
              update-types:
                  - 'minor'
                  - 'patch'

    # Track updates in @lunarisapp/hyphen's LibreOffice dictionaries.
    - package-ecosystem: gitsubmodule
      directory: /
      schedule:
          interval: 'monthly'
          day: 'thursday'
          time: '08:00'
          timezone: 'Europe/Amsterdam'
